#!/bin/bash

# Automated Patch Management Script for Political Sphere
# This script handles dependency updates, security patches, and automated testing

set -e

echo "🚀 Starting Automated Patch Management..."

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to log messages
log() {
    echo -e "${GREEN}[$(date +'%Y-%m-%d %H:%M:%S')] $1${NC}"
}

error() {
    echo -e "${RED}[$(date +'%Y-%m-%d %H:%M:%S')] ERROR: $1${NC}"
}

warn() {
    echo -e "${YELLOW}[$(date +'%Y-%m-%d %H:%M:%S')] WARNING: $1${NC}"
}

# Check if we're in a git repository
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    error "Not in a git repository"
    exit 1
fi

# Create a new branch for patch updates
BRANCH_NAME="patch-update-$(date +%Y%m%d-%H%M%S)"
log "Creating patch branch: $BRANCH_NAME"
git checkout -b "$BRANCH_NAME"

# Update dependencies
log "Updating npm dependencies..."
npm audit fix

# Run security audit and fix
log "Running security audit..."
npm audit fix

# Check for outdated packages
log "Checking for outdated packages..."
npm outdated || true

# Run tests to ensure everything still works
log "Running tests..."
npm run test

# Run linting
log "Running linting..."
npm run lint

# Check if there are changes to commit
if git diff --quiet && git diff --staged --quiet; then
    log "No changes to commit"
    git checkout main
    git branch -D "$BRANCH_NAME"
    exit 0
fi

# Commit changes
log "Committing patch updates..."
git add .
git commit -m "chore: automated patch management

- Updated dependencies
- Fixed security vulnerabilities
- Applied automated patches

Generated by patch-management.sh"

# Push the branch
log "Pushing patch branch..."
git push origin "$BRANCH_NAME"

# Create a pull request (requires GitHub CLI)
if command -v gh &> /dev/null; then
    log "Creating pull request..."
    gh pr create \
        --title "Automated Patch Management" \
        --body "This PR contains automated dependency updates and security patches.

## Changes
- Updated npm dependencies
- Fixed security vulnerabilities
- Applied automated patches

## Testing
- All tests pass
- Linting passes
- Security audit clean

Auto-generated by patch-management.sh" \
        --label "automated,patch,security"
else
    warn "GitHub CLI not found. Please create a PR manually for branch: $BRANCH_NAME"
fi

log "✅ Patch management completed successfully!"
log "Branch: $BRANCH_NAME"

# Switch back to main
git checkout main
