import { z } from 'zod';

/**
 * PartySchema
 *
 * Zod schema describing a political party entity used across the system.
 * - `id`: UUID string uniquely identifying a party
 * - `name`: Full display name of the party
 * - `abbreviation`: Optional short name or acronym (e.g., "Con")
 */
export const PartySchema = z.object({
  id: z.string().uuid(),
  name: z.string().min(1).max(100),
  description: z.string().max(500).optional(),
  color: z.string().regex(/^#[0-9A-Fa-f]{6}$/),
  createdAt: z.date(),
});

/**
 * Type: Party
 * - Inferred from `PartySchema` for compile-time type safety.
 */
export type Party = z.infer<typeof PartySchema>;

/**
 * Zod schema for validating payloads used when creating a Party.
 * Excludes server-populated fields such as `id` and `createdAt`.
 */
export const CreatePartySchema = z.object({
  name: z.string().min(1).max(100),
  description: z.string().max(500).optional(),
  color: z.string().regex(/^#[0-9A-Fa-f]{6}$/),
});

/**
 * Type: CreatePartyInput
 * - Inferred from `CreatePartySchema`.
 */
export type CreatePartyInput = z.infer<typeof CreatePartySchema>;

/**
 * Alias for CreatePartyInput for backward compatibility
 */
export type PartyCreate = CreatePartyInput;

/**
 * PartyCreate
 *
 * Input shape for creating a new party. Note: `id` is omitted because it is
 * typically generated by the backend datastore.
 */
export const UpdatePartySchema = z
  .object({
    name: z.string().min(1).max(100).optional(),
    description: z.string().max(500).optional(),
    color: z.string().regex(/^#[0-9A-Fa-f]{6}$/).optional(),
  })
  .refine((data) => Object.keys(data).length > 0, {
    message: 'At least one field must be provided for update',
  });

/**
 * Type: UpdatePartyInput
 * - Inferred from `UpdatePartySchema` and used for update handlers.
 */
export type UpdatePartyInput = z.infer<typeof UpdatePartySchema>;

/**
 * PartyUpdate
 *
 * Input shape for partial updates to a Party. Every field is optional so
 * callers can provide only the fields they want to change.
 */
export type PartyUpdate = Partial<PartyCreate>;
